<a href="https://colab.research.google.com/github/KaiberSo/FoodFactory/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

In [2]:
import numpy as np


NUMPY ARRAY

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


2d ARRAY

In [4]:
a=np.array([(1,2,3,4),(2,3,4,5)])
print(a)

[[1 2 3 4]
 [2 3 4 5]]


3D ARRAY

In [5]:
a=np.array([(1,2,3,4),(2,3,4,5),(3,4,5,6)])
print(a)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


FLOATING POINT ARRAY

In [6]:
a=np.array([(1,2,3,4),(2,3,4,5),(3,4,5,6)] , dtype=float)
print(a)

[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]


ZERO ARRAY

In [8]:
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


ONES ARRAY

In [9]:
a=np.ones((4,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


INDENTITY MATRIX

In [12]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


EVENLY SPACE VALUE

In [14]:
a=np.linspace(0,20,4)
print(a)

[ 0.          6.66666667 13.33333333 20.        ]


ARRAY FROM RANDOM VALUE

2 is row and 3 is column

In [17]:
a=np.random.random((2,3))
print(a)

[[0.48607842 0.19055055 0.12068447]
 [0.23424283 0.34366282 0.63114404]]


RANDOM VALUE INTEGER

0 is starting number 100 is ending and 3 and 4 are row and column

In [19]:
a=np.random.randint(0,100,(3,4))
print(a)

[[63 82 56 16]
 [91 41 30 14]
 [ 8 58 29  4]]


LIST TO NUMPY ARRAY

In [24]:
list1=[1,2,3,4,5]
print (list1)
type(list1)

a=np.asarray(list1)
print(a)
type(a)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


numpy.ndarray

ARRAY DIMENSION
NO OF DIMENSION
SIZE OF ELEMENTS

In [25]:
a=np.random.randint(1,20,(3,4))
print(a)

print(a.shape)

print(a.ndim)

print(a.size)


[[17 13  2 19]
 [ 5  9 13  4]
 [19 17  3 18]]
(3, 4)
2
12


ADDITION
SUB
MUL
DIV

In [26]:
a=np.random.randint(10,20,(3,4))
b=np.random.randint(10,20,(3,4))

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[30 34 31 38]
 [24 25 31 37]
 [28 35 29 30]]
[[-8 -4 -3  0]
 [ 0 -3  1  1]
 [-8 -3  7 -8]]
[[209 285 238 361]
 [144 154 240 342]
 [180 304 198 209]]
[[0.57894737 0.78947368 0.82352941 1.        ]
 [1.         0.78571429 1.06666667 1.05555556]
 [0.55555556 0.84210526 1.63636364 0.57894737]]
